sudo: true
notifications:
email: false
language: java
jdk:
  - openjdk7
  - oraclejdk7
env:
global:
install:
- sudo apt-get update -qq
- sudo apt-get install libtool subversion maven g++ openjdk-7-jdk dos2unix icoutils -qq
- git clone https://github.com/bengtmartensson/harctoolboxbundle.git
script:
- cd ./harctoolboxbundle
- ./tools/build-decodeir.sh 
- ./tools/build-exchangeir.sh 
- ./tools/build-jcommander.sh
- ./tools/build-minimal-json.sh 
- sudo mkdir -p /etc/alternatives/java_sdk/jre/lib/amd64/
- sudo ln -s /usr/lib/amd64/libjava.so /etc/alternatives/java_sdk/jre/lib/amd64/
- ./tools/build-tonto.sh 
- ./tools/build-wakeonlan.sh 
- mvn package
- ls -lh ./IrScrutinizer/target/IrScrutinizer-bin.zip
before_deploy: git fetch --tags
deploy:
provider: releases
api_key:
secure: 
skip_cleanup: true
file_glob: true
file: $TRAVIS_BUILD_DIR/*.ipk
on:
tags: true
all_branches: true
