sudo: true
notifications:
email: false
language: java
jdk:
  - openjdk7
env:
global:
install:
- sudo apt-get update -qq
- sudo apt-get install libtool subversion maven g++ openjdk-7-jdk dos2unix icoutils python-requests -qq
- git clone https://github.com/probonopd/harctoolboxbundle.git
script:
- cd ./harctoolboxbundle
- ./tools/build-decodeir.sh 
- ./tools/build-exchangeir.sh 
- ./tools/build-jcommander.sh
- ./tools/build-minimal-json.sh 
- sudo mkdir -p /etc/alternatives/java_sdk/jre/lib/amd64/
- sudo ln -s /usr/lib/amd64/libjava.so /etc/alternatives/java_sdk/jre/lib/amd64/
- ./tools/build-tonto.sh || echo "continuing"
- ./tools/build-wakeonlan.sh 
- mvn package
- ls -lh ./IrScrutinizer/target/IrScrutinizer-bin.zip
- wget https://raw.githubusercontent.com/probonopd/travis2github/master/travis2github.py
- wget https://raw.githubusercontent.com/probonopd/travis2github/master/magic.py
- python travis2github.py ./IrScrutinizer/target/IrScrutinizer-bin.zip
before_deploy: git fetch --tags
deploy:
provider: releases
api_key: e1qiIqcPPMVwziD3msCV3ww91TeeANQ96btn3LxYIk0WDoN89oCc1GOtmHEb2/PgtAT0OCXtYzBS6pWdEN8jfZaETv8J5STaBC7SRqdYG5CYdQNQ4H6juTKgtQ89SgvCp1cZ8I45eQihg+bdB5NY9V2haQCYWEcJ2w+2uR6lRmv2Bg+8gLgni4dvhpzgK4gFVXMEu0RCdkLIbGGaWA4NXkyxVEiAZhKjM7TeT4nbwFcoGeXVl15SZpKc/VG9fiRP04MegsxCre036/zcBTd5kQXq1gAyCmxno50ZO9baPh9O8u5yRaCbGCKEQoIk96Ky+Z2EvSXDUuG6jgw0V1ruIIMlVn3cmg/467Ff/cbc5+6FRJj1AxhMA5LiBahRAhkB9SbQLnD6lc6oq4LF4VskR3Z1CHKIIWfLOhimcGl0jt1of7kNCwo9W1F3N3hph8QbfFrnWbUvm5pImO1BpBU2oCFVJ6Id/zGkaI4HnV6dF6BJaKl+eX4sckTmyBfVnOw5WK1TMp9TcXF/Z/AhEAwmhpFl04KGIBX+Wn/ETKe9eGURoXWLvLd4lNQxAtfpcswL9nSUzpeQT3S2dDG/QTnHppZgoyKhQCop6Za7QqCfodYjPmDt6PLBkZvqF/skX7mXvFuo6FrXkOvZi8XM5B0xc1WvxQwkb0aMjmE8kLNLvXc=
secure: 
skip_cleanup: true
file_glob: true
file: $TRAVIS_BUILD_DIR/harctoolboxbundle/IrScrutinizer/target/IrScrutinizer-bin.zip
on:
tags: true
all_branches: true
