sudo: true
notifications:
email: false
language: java
jdk:
  - openjdk7
env:
global:
install:
- sudo apt-get update -qq
- sudo apt-get install libtool subversion maven g++ openjdk-7-jdk autotools dos2unix icoutils python-requests -qq
script:
- ./tools/build-decodeir.sh 
- ./tools/build-exchangeir.sh 
- ./tools/build-jcommander.sh
- ./tools/build-minimal-json.sh 
- sudo mkdir -p /etc/alternatives/java_sdk/jre/lib/amd64/
- sudo ln -s /usr/lib/amd64/libjava.so /etc/alternatives/java_sdk/jre/lib/amd64/
- ./tools/build-tonto.sh || echo "continuing"
- ./tools/build-wakeonlan.sh 
- mvn package
- ls -lh ./IrScrutinizer/target/IrScrutinizer-bin.zip
- cd "./package/IrScrutinizer.app/Contents/Resources"
- unzip ../../../../IrScrutinizer/target/IrScrutinizer-bin.zip
- cd -
- cd ./package
- zip -r IrScrutinizer.app.zip IrScrutinizer.app
- cd -
- wget https://raw.githubusercontent.com/probonopd/travis2github/master/travis2github.py
- wget https://raw.githubusercontent.com/probonopd/travis2github/master/magic.py
- python travis2github.py ./IrScrutinizer/target/IrScrutinizer-bin.zip ./package/IrScrutinizer.app
