#!/bin/bash

HERE=$(cd "$(dirname "$0")"; pwd)

RES="${HERE}/../Resources"

# Set to the preferred Java VM
JAVA=java

LIBRARY_PATH="${RES}/lib"

exec "${JAVA}" -Djava.library.path="${LIBRARY_PATH}" -Xdock:icon="${RES}/IrScrutinizer.icns" -Xdock:name="IrScrutinizer" -jar "${RES}/IrScrutinizer-jar-with-dependencies.jar" -p "${HOME}/.IrScrutinizer.properties.xml"
